In [ ]:
from time import perf_counter
from functools import wraps

def medir_tiempo(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        inicio = perf_counter()
        resultado = func(*args, **kwargs)
        fin = perf_counter()
        print(f"Función '{func.__name__}' tardó: {fin - inicio:.6f} s")
        return resultado
    return wrapper

import numpy as np

@medir_tiempo
def crear_lista_python(n):
    return [i for i in range(n)]

@medir_tiempo
def crear_array_numpy(n):
    return np.arange(n)

# Prueba con 10 millones de elementos
n = 10_000_000
crear_lista_python(n)
crear_array_numpy(n)

Función 'crear_lista_python' tardó: 0.440216 s
Función 'crear_array_numpy' tardó: 0.014489 s


array([      0,       1,       2, ..., 9999997, 9999998, 9999999],
      shape=(10000000,))

In [ ]:
import numpy as np
n = 10_000_000

In [ ]:
%%timeit
[i for i in range(n)]

523 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
lista = [i for i in range(n)]

402 ms ± 6.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
lista = []
for i in range(n):
    lista.append(i)

460 ms ± 2.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.linspace(0,10,10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#probamos fibras
D = 20
n = 5

print(np.arange(0,D,D/n)+ n/2)
print(np.linspace(0,D,n, endpoint=False)+ n/2)
print([i*(D/n) + n/2 for i in range(n)])

[ 2.5  6.5 10.5 14.5 18.5]
[ 2.5  6.5 10.5 14.5 18.5]
[2.5, 6.5, 10.5, 14.5, 18.5]


In [ ]:
5*[i for i in range(5)]

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [1]:
import numpy as np
a = [5,8,4,1,4,9,4,2]
print(a)
b = np.asarray(a)
print(b)
idx = np.argsort(b)
print(idx)
c = b[idx]
print(c)


[5, 8, 4, 1, 4, 9, 4, 2]
[5 8 4 1 4 9 4 2]
[3 7 4 2 6 0 1 5]
[1 2 4 4 4 5 8 9]
